name: Test Parser-Core

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 8 * * *'

env:
  LOGGING_DEFAULT_SHOW_PREFIX: true
  LOGGING_DEFAULT_LOGGING_LEVEL: DEBUG
  LOGGING_DEFAULT_SHOW_FORMATTING: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.5.0
        with:
          java-version: 8
          maven-version: 3.8.6

      - uses: actions/checkout@v3

      - name: Download latest Airship
        uses: FlatLang/fetch-airship@master
        with:
          includePrerelease: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup Airship
        run: |
          node airship.js setup

      - name: Link Parser-Core
        run: |
          node airship.js install --link

      - name: Build Parser-Core Test
        run: |
          node airship.js install test -t es6

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test.js
          path: dist/test.js

      - name: Run Parser-Core Test
        run: |
          node airship.js run test